version: '3'

services:
  rbac-boilerplate-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRES_DATABASE=rbac-boilerplate
